version: "3.5"

services:
    php_fpm:
        build: .
        container_name: app_php_fpm
        networks:
            - app

    nginx:
        image: nginx:1.15
        container_name: nginx
        working_dir: /usr/share/nginx/app
        networks:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx/app
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
    app:
        driver: bridge